name: logist
description: LOGISTIC FROM THE FUTURE.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  country_icons: ^2.0.2
  ndialog: ^4.1.1
  awesome_dialog: ^2.2.1
  rflutter_alert: ^2.0.4
  flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.1
  sliding_up_panel: ^2.0.0+1
  get: ^4.6.5
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  permission_handler: ^10.2.0

  #  location: ^5.0.0-dev.8
  flutter_svg: ^1.1.3
  flutter_typeahead: ^4.0.0
  enhance_stepper: ^0.1.1
  im_stepper: ^1.0.1+1
  get_storage: ^2.0.3
  image_picker: ^0.8.6+2

  flutter_speed_dial: ^6.0.0
  skeletons: ^0.0.3
  flutter_launcher_icons: ^0.10.0
  percent_indicator: ^4.2.2
  flutter_native_splash: ^2.2.8
  custom_info_window: ^1.0.1
  fluttertoast: ^8.0.9
  credit_card_type_detector: ^2.0.0
  animations: ^2.0.4
  numberpicker: ^2.1.1
  shimmer: ^2.0.0
  animate_icons: ^2.0.0
  animated_rotation: ^2.0.0
  syncfusion_flutter_datepicker: ^20.2.46
  loading_animation_widget: ^1.2.0+3
  intl: ^0.17.0
  #map
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  overlay_support: ^2.1.0
  lottie: ^2.0.0
  # network Service
  http: ^0.13.4
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  logger: ^1.1.0
  #state managment
  provider: ^6.0.3
 
  #local database
  shared_preferences: ^2.0.12

flutter_native_splash:
#  color: "#191F28"
#  image: assets/Logist.png
#  android_12:
#    color: "#191F28"
#    image: assets/Logist.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Shamel
      fonts:
        - asset: fonts/FF Shamel Family Sans One Bold.ttf
    - family: ShamelThin
      fonts:
        - asset: fonts/FF Shamel Family Sans One Book.ttf
    - family: ArabotoThin
      fonts:
        - asset: fonts/Araboto Thin 400.ttf
    - family: Araboto
      fonts:
        - asset: fonts/Araboto Normal 400.ttf
    - family: ArabotoMedium
      fonts:
        - asset: fonts/Araboto Medium 400.ttf
    - family: ArabotoFat
      fonts:
        - asset: fonts/Araboto Bold 400.ttf
    - family: visbylight
      fonts:
        - asset: fonts/visbycf-light.otf
    - family: visbydemibold
      fonts:
        - asset: fonts/visbycf-demibold.otf
    - family: ArabotoNormal
      fonts:
        - asset: fonts/Araboto500.ttf
    - family: BottomBarIcons
      fonts:
        - asset: fonts/BottomBarIcons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ArabicExtraLight.otf
          weight: 200
        - asset: fonts/Montserrat-ArabicBlack.otf
          weight: 900
        - asset: fonts/Montserrat-ArabicMedium.otf
          weight: 500
        - asset: fonts/Montserrat-ArabicRegular.otf
          weight: 400
        - asset: fonts/Montserrat-ArabicLight.otf
          weight: 300
    - family: STC
      fonts:
        - asset: fonts/STC-Bold.ttf
          weight: 700
    - family: circular std
      fonts:
        - asset: fonts/circular std.ttf
        - asset: fonts/CircularStd-light.ttf
          weight: 200
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
    - family: lexend
      fonts:
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
    - family: Madani
      fonts:
        - asset: fonts/Madani Arabic Regular.ttf
        - asset: fonts/Madani Arabic Thin.ttf
          weight: 100
        - asset: fonts/Madani Arabic Extra Light.ttf
          weight: 200
        - asset: fonts/Madani Arabic Light.ttf
          weight: 300
        - asset: fonts/Madani Arabic Medium.ttf
          weight: 500
        - asset: fonts/Madani Arabic Semi Bold.ttf
          weight: 600
        - asset: fonts/Madani Arabic Bold.ttf
          weight: 700
        - asset: fonts/Madani Arabic Extra Bold.ttf
          weight: 800
        - asset: fonts/Madani Arabic Black.ttf
          weight: 900


  assets:
    - assets/pics/
    - assets/json/
    - assets/
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

