/// Flutter icons BottomBarIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomBarIcons
///      fonts:
///       - asset: fonts/BottomBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'BottomBarIcons';
  static const String? _kFontPkg = null;

  static const IconData messagesoff_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageson = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messagesoff = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
